name: flyrigloader-dev
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Runtime Dependencies
  - python>=3.8,<3.12
  - loguru>=0.7.0
  - pydantic>=2.6
  - numpy>=1.21.0
  - pandas>=1.3.0
  
  # Testing Infrastructure
  - pytest>=7.0.0
  - pytest-cov>=6.1.1          # Coverage reporting with subprocess and xdist support
  - pytest-mock>=3.14.1        # Enhanced mocking capabilities with type safety
  - pytest-benchmark>=4.0.0    # Performance testing and regression detection
  - coverage>=7.8.2            # Core coverage measurement with modern monitoring
  - hypothesis>=6.131.9        # Property-based testing for robust validation
  - pytest-xdist>=3.7.0        # Parallel test execution across multiple CPUs
  - pytest-timeout>=2.3.0      # Test timeout management for CI/CD reliability
  
  # Code Quality & Pre-commit Infrastructure
  - black>=24.3.0              # Uncompromising code formatter
  - isort>=5.12.0              # Import sorting with black compatibility profile
  - mypy>=1.8.0                # Static type checking for enhanced code safety
  - flake8>=7.0.0              # Comprehensive linting and style enforcement
  - pre-commit>=3.6.0          # Git hook framework for automated quality gates
  
  # Build System Dependencies
  - setuptools>=42
  - wheel
  - pip
  
  # Development Tools
  - pip:
      - -e .  # Editable installation for development
